// REGISTER USER
POST http:/localhost:3000/auth/register
Content-Type: application/json
{
    "name": "julian",
    "lastname": "picapiedra",
    "nick": "jpica",
    "email": "jpica@gmail.com",
    "rolId": 2
}

// LOGIN
POST http:/localhost:3000/auth/login
Content-Type: application/json
{
  "email": "admin@root.com"
}

// FIND USER BY ID
GET http:/localhost:3000/auth/id/5

// MODIFY USER PROFILE
PUT http:/localhost:3000/auth/id/5
Content-Type: application/json
{
  "name": "marcos",
  "lastname": "tarazona",
  "nick": "mtarazona",
  "email": "mtarazona@gmail.com"
}

// DELETE USER PROFILE (ONLY ADMIN)
DELETE http:/localhost:3000/auth/id/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xJZCI6MSwibmljayI6ImFkbWluIiwiaWF0IjoxNjY3Njc3MTkxfQ.DINdHrQkeDpCIUR1L7fB9h6uJ5Fvbij6kYmRd6fHsM4