// NEW ORDER
POST http:/localhost:3000/rentals/loan
Content-Type: application/json
{
    "start_loan": "2022-11-06 12:30:00",
    "loan_ends": "2022-11-21 12:30:00",
    "userId": 4,
    "articleId": [6, 9]
}

// MODIFY ORDER
PATCH http:/localhost:3000/rentals/loan/22
Content-Type: application/json
{
    "articlesId": [
        {"articleId": 10},
        {"articleId": 11}
    ]
}

// GET ALL ORDERS ONE USER
GET http:/localhost:3000/rentals/loan/1

// GET ALL ORDERS IN DB (ONLY ADMIN)
GET http:/localhost:3000/rentals/loans
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xJZCI6MSwibmljayI6ImFkbWluIiwiaWF0IjoxNjY3Njc3MTkxfQ.DINdHrQkeDpCIUR1L7fB9h6uJ5Fvbij6kYmRd6fHsM4